networks:
  backend:
    external: true
  default:
    driver_opts:
      com.docker.network.driver.mtu: '1400'
  frontend:
    external: true
secrets:
  traefik.toml:
    file: /Users/tomas/Dev/smartsdk-recipes/recipes/data-management/quantumleap/traefik.toml
services:
  crate:
    command:
    - crate
    - -Clicense.enterprise=false
    - -Cgateway.expected_nodes=3
    - -Cgateway.recover_after_nodes=2
    - -Cgateway.recover_after_time=5m
    - -Cdiscovery.zen.minimum_master_nodes=2
    - -Cdiscovery.zen.ping.unicast.hosts=crate
    - -Cnetwork.host=0.0.0.0
    - -Ccluster.name=quantumleap
    - -Chttp.cors.enabled=true
    - -Chttp.cors.allow-origin="*"
    deploy:
      endpoint_mode: dnsrr
      labels:
      - traefik.port=4200
      - traefik.frontend.rule=Host:crate.mydomain.com
      - traefik.backend.loadbalancer.sticky=true
      - traefik.backend=crate
      - traefik.backend.loadbalancer.swarm=false
      - traefik.frontend.passHostHeader=true
      - traefik.backend.circuitbreaker.expression=NetworkErrorRatio() > 0.5
      - traefik.docker.network=frontend
      mode: global
      update_config:
        delay: 10s
        parallelism: 1
    environment:
      CRATE_HEAP_SIZE: 1g
      ES_JAVA_OPTS: '"-Xms512m -Xmx512m"'
      MAX_MAP_COUNT: '262144'
    image: crate:1.0.5
    networks:
      backend: null
      frontend: null
    volumes:
    - cratedata:/data:rw
  grafana:
    depends_on:
    - crate
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
    environment:
      GF_INSTALL_PLUGINS: crate-datasource,grafana-clock-panel,grafana-worldmap-panel
    image: grafana/grafana
    networks:
      backend: null
      frontend: null
    ports:
    - published: 3000
      target: 3000
  quantumleap:
    depends_on:
    - crate
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1m
        parallelism: 1
    environment:
      CRATE_HOST: crate
    image: smartsdk/quantumleap
    networks:
      backend: null
      frontend: null
    ports:
    - published: 8668
      target: 8668
  traefik:
    command:
    - --web
    - --docker
    - --docker.watch
    - --docker.swarmmode
    - --docker.domain=mydomain.com
    - --docker.endpoint=unix:///var/run/docker.sock
    - --debug=true
    - --logLevel=DEBUG
    - --configFile=/run/secrets/traefik.toml
    deploy:
      labels:
      - traefik.enable=false
      mode: global
      placement:
        constraints:
        - node.role==manager
      resources:
        limits:
          cpus: '0.30'
          memory: 72M
        reservations:
          cpus: '0.10'
          memory: 36M
      restart_policy:
        condition: on-failure
    image: traefik:1.3.5-alpine
    networks:
      frontend: null
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    - published: 4200
      target: 4200
    - published: 4300
      target: 4300
    - published: 8080
      target: 8080
    secrets:
    - source: traefik.toml
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.3'
volumes:
  cratedata: {}

